export const buildings = [
  {
    name: "Göbekli Tepe",
    location: "Türkiye",
    continent: "Asia",
    constructionPeriod: "c. 9600–8200 BCE",
    originalPurposeCategories: ["Worship", "Gather & Entertain"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "Great Pyramid of Giza",
    location: "Egypt",
    continent: "Africa",
    constructionPeriod: "c. 2580–2560 BCE",
    originalPurposeCategories: ["Remember & Honor", "Rule & Reside"],
    purposeTodayCategories: ["Visit & Preserve"],
  },
  {
    name: "Ziggurat of Ur",
    location: "Iraq",
    continent: "Asia",
    constructionPeriod: "c. 2100 BCE",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve"],
  },
  {
    name: "Karnak Temple Complex",
    location: "Egypt",
    continent: "Africa",
    constructionPeriod: "c. 2055 BCE–100 CE",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve"],
  },
  {
    name: "Palace of Knossos",
    location: "Crete, Greece",
    continent: "Europe",
    constructionPeriod: "c. 1900–1400 BCE",
    originalPurposeCategories: ["Rule & Reside", "Govern & Serve", "Worship"],
    purposeTodayCategories: ["Visit & Preserve"],
  },
  {
    name: "Treasury of Atreus",
    location: "Mycenae, Greece",
    continent: "Europe",
    constructionPeriod: "c. 1250 BCE",
    originalPurposeCategories: ["Remember & Honor", "Rule & Reside"],
    purposeTodayCategories: ["Visit & Preserve"],
  },
  {
    name: "Sanchi Stupa No. 1",
    location: "India",
    continent: "Asia",
    constructionPeriod: "3rd century BCE; enlarged c. 1st century BCE",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve", "Worship"],
  },
  {
    name: "Parthenon",
    location: "Athens, Greece",
    continent: "Europe",
    constructionPeriod: "447–432 BCE",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve"],
  },
  {
    name: "Apadana at Persepolis",
    location: "Iran",
    continent: "Asia",
    constructionPeriod: "c. 515–465 BCE",
    originalPurposeCategories: ["Rule & Reside", "Gather & Entertain"],
    purposeTodayCategories: ["Visit & Preserve"],
  },
  {
    name: "Temple of Hephaestus",
    location: "Athens, Greece",
    continent: "Europe",
    constructionPeriod: "c. 449–415 BCE",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve"],
  },
  {
    name: "Great Stupa at Amaravati",
    location: "India",
    continent: "Asia",
    constructionPeriod: "c. 3rd century BCE–3rd century CE",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "Library of Celsus",
    location: "Ephesus, Türkiye",
    continent: "Asia",
    constructionPeriod: "c. 110–135 CE",
    originalPurposeCategories: ["Remember & Honor", "Learn & Create"],
    purposeTodayCategories: ["Visit & Preserve"],
  },
  {
    name: "Pantheon",
    location: "Rome, Italy",
    continent: "Europe",
    constructionPeriod: "c. 118–125 CE",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve"],
  },
  {
    name: "Colosseum",
    location: "Rome, Italy",
    continent: "Europe",
    constructionPeriod: "72–80 CE",
    originalPurposeCategories: ["Gather & Entertain"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "Maison Carrée",
    location: "Nîmes, France",
    continent: "Europe",
    constructionPeriod: "c. 2–5 CE",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve"],
  },
  {
    name: "Diocletian’s Palace",
    location: "Split, Croatia",
    continent: "Europe",
    constructionPeriod: "c. 295–305 CE",
    originalPurposeCategories: ["Rule & Reside", "Defend"],
    purposeTodayCategories: [
      "Visit & Preserve",
      "Live & Work",
      "Govern & Serve",
    ],
  },
  {
    name: "Great Bath of the Roman Baths",
    location: "Bath, United Kingdom",
    continent: "Europe",
    constructionPeriod: "Mainly 1st–4th centuries CE",
    originalPurposeCategories: ["Gather & Entertain"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "Temple of the Inscriptions",
    location: "Palenque, Mexico",
    continent: "North America",
    constructionPeriod: "7th century CE",
    originalPurposeCategories: ["Worship", "Remember & Honor"],
    purposeTodayCategories: ["Visit & Preserve"],
  },
  {
    name: "Pyramid of the Sun",
    location: "Teotihuacan, Mexico",
    continent: "North America",
    constructionPeriod: "c. 100–250 CE",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "Tikal Temple I",
    location: "Guatemala",
    continent: "North America",
    constructionPeriod: "c. 732 CE",
    originalPurposeCategories: ["Worship", "Remember & Honor"],
    purposeTodayCategories: ["Visit & Preserve"],
  },
  {
    name: "Hagia Sophia",
    location: "Istanbul, Türkiye",
    continent: "Europe",
    constructionPeriod: "532–537",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve", "Worship"],
  },
  {
    name: "Basilica of San Vitale",
    location: "Ravenna, Italy",
    continent: "Europe",
    constructionPeriod: "526–547",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve", "Worship"],
  },
  {
    name: "Hōryū-ji",
    location: "Nara Prefecture, Japan",
    continent: "Asia",
    constructionPeriod: "Late 7th–early 8th century",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve"],
  },
  {
    name: "Dome of the Rock",
    location: "Jerusalem",
    continent: "Asia",
    constructionPeriod: "691–692",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Worship"],
  },
  {
    name: "Umayyad Mosque",
    location: "Damascus, Syria",
    continent: "Asia",
    constructionPeriod: "706–715",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve", "Worship"],
  },
  {
    name: "Borobudur",
    location: "Java, Indonesia",
    continent: "Asia",
    constructionPeriod: "c. 780–830",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve", "Worship"],
  },
  {
    name: "Prambanan",
    location: "Java, Indonesia",
    continent: "Asia",
    constructionPeriod: "c. 850",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve", "Worship"],
  },
  {
    name: "Great Mosque of Samarra",
    location: "Iraq",
    continent: "Asia",
    constructionPeriod: "848–852",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve"],
  },
  {
    name: "Aachen Cathedral",
    location: "Germany",
    continent: "Europe",
    constructionPeriod: "c. 796–805; later additions",
    originalPurposeCategories: ["Worship", "Rule & Reside"],
    purposeTodayCategories: ["Visit & Preserve", "Worship"],
  },
  {
    name: "Jokhang Temple",
    location: "Lhasa, Tibet",
    continent: "Asia",
    constructionPeriod: "7th century; later additions",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve", "Worship"],
  },
  {
    name: "Brihadisvara Temple",
    location: "Thanjavur, India",
    continent: "Asia",
    constructionPeriod: "1003–1010",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve"],
  },
  {
    name: "Angkor Wat",
    location: "Cambodia",
    continent: "Asia",
    constructionPeriod: "Early 12th century",
    originalPurposeCategories: ["Worship", "Remember & Honor"],
    purposeTodayCategories: ["Visit & Preserve", "Worship"],
  },
  {
    name: "Durham Cathedral",
    location: "United Kingdom",
    continent: "Europe",
    constructionPeriod: "1093–1133",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve"],
  },
  {
    name: "Chartres Cathedral",
    location: "France",
    continent: "Europe",
    constructionPeriod: "Mainly 1194–1220",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve", "Worship"],
  },
  {
    name: "Hoysaleswara Temple",
    location: "Halebidu, India",
    continent: "Asia",
    constructionPeriod: "c. 1121–1160",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve", "Worship"],
  },
  {
    name: "Church of St George, Lalibela",
    location: "Ethiopia",
    continent: "Africa",
    constructionPeriod: "Late 12th–early 13th century",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve", "Worship"],
  },
  {
    name: "Qutb Minar",
    location: "Delhi, India",
    continent: "Asia",
    constructionPeriod: "1199–early 14th century",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve"],
  },
  {
    name: "Konark Sun Temple",
    location: "Odisha, India",
    continent: "Asia",
    constructionPeriod: "c. 1238–1250",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve"],
  },
  {
    name: "Sainte-Chapelle",
    location: "Paris, France",
    continent: "Europe",
    constructionPeriod: "1241–1248",
    originalPurposeCategories: ["Worship", "Remember & Honor", "Rule & Reside"],
    purposeTodayCategories: [
      "Visit & Preserve",
      "Worship",
      "Learn & Experience",
    ],
  },
  {
    name: "Great Enclosure at Great Zimbabwe",
    location: "Zimbabwe",
    continent: "Africa",
    constructionPeriod: "c. 13th–15th century",
    originalPurposeCategories: ["Rule & Reside", "Govern & Serve"],
    purposeTodayCategories: ["Visit & Preserve"],
  },
  {
    name: "Alhambra",
    location: "Granada, Spain",
    continent: "Europe",
    constructionPeriod: "Mainly 13th–14th centuries",
    originalPurposeCategories: ["Rule & Reside", "Defend", "Govern & Serve"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "Forbidden City",
    location: "Beijing, China",
    continent: "Asia",
    constructionPeriod: "1406–1420",
    originalPurposeCategories: ["Rule & Reside", "Govern & Serve"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "Kinkaku-ji",
    location: "Kyoto, Japan",
    continent: "Asia",
    constructionPeriod: "1397; reconstructed 1955",
    originalPurposeCategories: ["Worship", "Rule & Reside"],
    purposeTodayCategories: ["Visit & Preserve"],
  },
  {
    name: "Machu Picchu",
    location: "Peru",
    continent: "South America",
    constructionPeriod: "c. 1450",
    originalPurposeCategories: ["Rule & Reside", "Worship"],
    purposeTodayCategories: ["Visit & Preserve"],
  },
  {
    name: "Florence Cathedral",
    location: "Italy",
    continent: "Europe",
    constructionPeriod: "1296–1436",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve", "Worship"],
  },
  {
    name: "Doge’s Palace",
    location: "Venice, Italy",
    continent: "Europe",
    constructionPeriod: "Mainly 14th–15th centuries",
    originalPurposeCategories: ["Rule & Reside", "Govern & Serve"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "Elmina Castle",
    location: "Ghana",
    continent: "Africa",
    constructionPeriod: "1482",
    originalPurposeCategories: ["Trade & Produce", "Defend"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "Château de Chambord",
    location: "France",
    continent: "Europe",
    constructionPeriod: "1519–1547",
    originalPurposeCategories: ["Rule & Reside"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "St Peter’s Basilica",
    location: "Vatican City",
    continent: "Europe",
    constructionPeriod: "1506–1626",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve", "Worship"],
  },
  {
    name: "Humayun’s Tomb",
    location: "Delhi, India",
    continent: "Asia",
    constructionPeriod: "1565–1572",
    originalPurposeCategories: ["Remember & Honor", "Rule & Reside"],
    purposeTodayCategories: ["Visit & Preserve"],
  },
  {
    name: "Süleymaniye Mosque",
    location: "Istanbul, Türkiye",
    continent: "Europe",
    constructionPeriod: "1550–1557",
    originalPurposeCategories: [
      "Worship",
      "Rule & Reside",
      "Gather & Entertain",
    ],
    purposeTodayCategories: ["Visit & Preserve", "Worship"],
  },
  {
    name: "St Basil’s Cathedral",
    location: "Moscow, Russia",
    continent: "Europe",
    constructionPeriod: "1555–1561",
    originalPurposeCategories: ["Worship", "Remember & Honor", "Defend"],
    purposeTodayCategories: [
      "Visit & Preserve",
      "Worship",
      "Learn & Experience",
    ],
  },
  {
    name: "Temple of Heaven",
    location: "Beijing, China",
    continent: "Asia",
    constructionPeriod: "1420; later rebuilt and expanded",
    originalPurposeCategories: ["Worship", "Govern & Serve"],
    purposeTodayCategories: ["Visit & Preserve", "Govern & Serve"],
  },
  {
    name: "Himeji Castle",
    location: "Japan",
    continent: "Asia",
    constructionPeriod: "Mainly 1601–1609",
    originalPurposeCategories: ["Rule & Reside", "Defend", "Govern & Serve"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "Sultan Ahmed Mosque",
    location: "Istanbul, Türkiye",
    continent: "Europe",
    constructionPeriod: "1609–1616",
    originalPurposeCategories: ["Worship", "Rule & Reside"],
    purposeTodayCategories: ["Visit & Preserve", "Worship"],
  },
  {
    name: "Shah Mosque",
    location: "Isfahan, Iran",
    continent: "Asia",
    constructionPeriod: "1611–1629",
    originalPurposeCategories: ["Worship", "Rule & Reside"],
    purposeTodayCategories: ["Visit & Preserve", "Worship"],
  },
  {
    name: "Taj Mahal",
    location: "Agra, India",
    continent: "Asia",
    constructionPeriod: "1632–1653",
    originalPurposeCategories: ["Remember & Honor"],
    purposeTodayCategories: ["Visit & Preserve"],
  },
  {
    name: "Potala Palace",
    location: "Lhasa, Tibet",
    continent: "Asia",
    constructionPeriod: "Mainly 1645–1694",
    originalPurposeCategories: ["Rule & Reside", "Govern & Serve", "Worship"],
    purposeTodayCategories: [
      "Visit & Preserve",
      "Worship",
      "Learn & Experience",
    ],
  },
  {
    name: "Palace of Versailles",
    location: "France",
    continent: "Europe",
    constructionPeriod: "Mainly 1661–1715",
    originalPurposeCategories: ["Rule & Reside", "Govern & Serve"],
    purposeTodayCategories: [
      "Visit & Preserve",
      "Learn & Experience",
      "Govern & Serve",
    ],
  },
  {
    name: "St Paul’s Cathedral",
    location: "London, United Kingdom",
    continent: "Europe",
    constructionPeriod: "1675–1710",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve", "Worship"],
  },
  {
    name: "Royal Palace of Caserta",
    location: "Italy",
    continent: "Europe",
    constructionPeriod: "1752–1845",
    originalPurposeCategories: ["Rule & Reside", "Govern & Serve"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "Panthéon",
    location: "Paris, France",
    continent: "Europe",
    constructionPeriod: "1758–1790",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Visit & Preserve"],
  },
  {
    name: "Royal Crescent",
    location: "Bath, United Kingdom",
    continent: "Europe",
    constructionPeriod: "1767–1775",
    originalPurposeCategories: ["Live & Work"],
    purposeTodayCategories: ["Visit & Preserve", "Live & Work"],
  },
  {
    name: "Monticello",
    location: "Virginia, United States",
    continent: "North America",
    constructionPeriod: "1769–1809",
    originalPurposeCategories: ["Live & Work", "Trade & Produce"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "United States Capitol",
    location: "Washington, D.C.",
    continent: "North America",
    constructionPeriod: "1793–1826; later expansions",
    originalPurposeCategories: ["Govern & Serve"],
    purposeTodayCategories: ["Govern & Serve", "Visit & Preserve"],
  },
  {
    name: "Brandenburg Gate",
    location: "Berlin, Germany",
    continent: "Europe",
    constructionPeriod: "1788–1791",
    originalPurposeCategories: ["Govern & Serve", "Gather & Entertain"],
    purposeTodayCategories: ["Visit & Preserve", "Govern & Serve"],
  },
  {
    name: "British Museum",
    location: "London, United Kingdom",
    continent: "Europe",
    constructionPeriod: "Main building 1823–1852",
    originalPurposeCategories: ["Learn & Create"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "Palace of Westminster",
    location: "London, United Kingdom",
    continent: "Europe",
    constructionPeriod: "1840–1876",
    originalPurposeCategories: ["Govern & Serve"],
    purposeTodayCategories: ["Govern & Serve", "Visit & Preserve"],
  },
  {
    name: "Bibliothèque Sainte-Geneviève",
    location: "Paris, France",
    continent: "Europe",
    constructionPeriod: "1843–1850",
    originalPurposeCategories: ["Learn & Create"],
    purposeTodayCategories: ["Learn & Experience", "Govern & Serve"],
  },
  {
    name: "Crystal Palace",
    location: "London, United Kingdom",
    continent: "Europe",
    constructionPeriod: "1850–1851",
    originalPurposeCategories: ["Gather & Entertain", "Trade & Produce"],
    purposeTodayCategories: ["Visit & Preserve", "Restore & Complete"],
  },
  {
    name: "Red House",
    location: "Bexleyheath, United Kingdom",
    continent: "Europe",
    constructionPeriod: "1859–1860",
    originalPurposeCategories: ["Live & Work"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "Galleria Vittorio Emanuele II",
    location: "Milan, Italy",
    continent: "Europe",
    constructionPeriod: "1865–1877",
    originalPurposeCategories: ["Trade & Produce", "Gather & Entertain"],
    purposeTodayCategories: ["Visit & Preserve", "Live & Work"],
  },
  {
    name: "Chhatrapati Shivaji Maharaj Terminus",
    location: "Mumbai, India",
    continent: "Asia",
    constructionPeriod: "1878–1888",
    originalPurposeCategories: ["Travel & Connect", "Govern & Serve"],
    purposeTodayCategories: [
      "Govern & Serve",
      "Live & Work",
      "Visit & Preserve",
    ],
  },
  {
    name: "Eiffel Tower",
    location: "Paris, France",
    continent: "Europe",
    constructionPeriod: "1887–1889",
    originalPurposeCategories: ["Gather & Entertain"],
    purposeTodayCategories: ["Visit & Preserve", "Govern & Serve"],
  },
  {
    name: "Natural History Museum",
    location: "London, United Kingdom",
    continent: "Europe",
    constructionPeriod: "1873–1881",
    originalPurposeCategories: ["Learn & Create"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "Hungarian Parliament Building",
    location: "Budapest, Hungary",
    continent: "Europe",
    constructionPeriod: "1885–1904",
    originalPurposeCategories: ["Govern & Serve"],
    purposeTodayCategories: ["Govern & Serve", "Visit & Preserve"],
  },
  {
    name: "Wainwright Building",
    location: "St Louis, United States",
    continent: "North America",
    constructionPeriod: "1890–1891",
    originalPurposeCategories: ["Trade & Produce"],
    purposeTodayCategories: ["Govern & Serve", "Visit & Preserve"],
  },
  {
    name: "Flatiron Building",
    location: "New York, United States",
    continent: "North America",
    constructionPeriod: "1901–1902",
    originalPurposeCategories: ["Trade & Produce"],
    purposeTodayCategories: ["Visit & Preserve", "Restore & Complete"],
  },
  {
    name: "Casa Batlló",
    location: "Barcelona, Spain",
    continent: "Europe",
    constructionPeriod: "Remodelled 1904–1906",
    originalPurposeCategories: ["Live & Work"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "Glasgow School of Art, Mackintosh Building",
    location: "Glasgow, United Kingdom",
    continent: "Europe",
    constructionPeriod: "1897–1909",
    originalPurposeCategories: ["Learn & Create"],
    purposeTodayCategories: ["Learn & Experience", "Restore & Complete"],
  },
  {
    name: "AEG Turbine Factory",
    location: "Berlin, Germany",
    continent: "Europe",
    constructionPeriod: "1908–1909",
    originalPurposeCategories: ["Trade & Produce"],
    purposeTodayCategories: ["Live & Work", "Visit & Preserve"],
  },
  {
    name: "Robie House",
    location: "Chicago, United States",
    continent: "North America",
    constructionPeriod: "1909–1910",
    originalPurposeCategories: ["Live & Work"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "Fagus Factory",
    location: "Alfeld, Germany",
    continent: "Europe",
    constructionPeriod: "1911–1913",
    originalPurposeCategories: ["Trade & Produce"],
    purposeTodayCategories: ["Live & Work", "Visit & Preserve"],
  },
  {
    name: "Einstein Tower",
    location: "Potsdam, Germany",
    continent: "Europe",
    constructionPeriod: "1919–1922",
    originalPurposeCategories: ["Learn & Create"],
    purposeTodayCategories: ["Learn & Experience", "Govern & Serve"],
  },
  {
    name: "Bauhaus Building",
    location: "Dessau, Germany",
    continent: "Europe",
    constructionPeriod: "1925–1926",
    originalPurposeCategories: ["Learn & Create"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "Schröder House",
    location: "Utrecht, Netherlands",
    continent: "Europe",
    constructionPeriod: "1923–1924",
    originalPurposeCategories: ["Live & Work"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "Villa Savoye",
    location: "Poissy, France",
    continent: "Europe",
    constructionPeriod: "1928–1931",
    originalPurposeCategories: ["Live & Work"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "Barcelona Pavilion",
    location: "Barcelona, Spain",
    continent: "Europe",
    constructionPeriod: "1928–1929; reconstructed 1983–1986",
    originalPurposeCategories: ["Gather & Entertain", "Govern & Serve"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "Chrysler Building",
    location: "New York, United States",
    continent: "North America",
    constructionPeriod: "1928–1930",
    originalPurposeCategories: ["Trade & Produce"],
    purposeTodayCategories: ["Live & Work", "Visit & Preserve"],
  },
  {
    name: "Empire State Building",
    location: "New York, United States",
    continent: "North America",
    constructionPeriod: "1930–1931",
    originalPurposeCategories: ["Trade & Produce"],
    purposeTodayCategories: ["Live & Work", "Visit & Preserve"],
  },
  {
    name: "Fallingwater",
    location: "Pennsylvania, United States",
    continent: "North America",
    constructionPeriod: "1936–1939",
    originalPurposeCategories: ["Live & Work"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "Paimio Sanatorium",
    location: "Finland",
    continent: "Europe",
    constructionPeriod: "1929–1933",
    originalPurposeCategories: ["Gather & Entertain"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "Secretariat Building",
    location: "Chandigarh, India",
    continent: "Asia",
    constructionPeriod: "1951–1958",
    originalPurposeCategories: ["Govern & Serve"],
    purposeTodayCategories: ["Govern & Serve"],
  },
  {
    name: "National Assembly Building",
    location: "Dhaka, Bangladesh",
    continent: "Asia",
    constructionPeriod: "1961–1982",
    originalPurposeCategories: ["Govern & Serve"],
    purposeTodayCategories: ["Govern & Serve"],
  },
  {
    name: "Brasília Cathedral",
    location: "Brazil",
    continent: "South America",
    constructionPeriod: "1958–1970",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: ["Worship"],
  },
  {
    name: "Sydney Opera House",
    location: "Sydney, Australia",
    continent: "Oceania",
    constructionPeriod: "1959–1973",
    originalPurposeCategories: ["Gather & Entertain", "Learn & Create"],
    purposeTodayCategories: ["Learn & Experience", "Visit & Preserve"],
  },
  {
    name: "Habitat 67",
    location: "Montreal, Canada",
    continent: "North America",
    constructionPeriod: "1964–1967",
    originalPurposeCategories: ["Live & Work"],
    purposeTodayCategories: ["Live & Work", "Visit & Preserve"],
  },
  {
    name: "Centre Pompidou",
    location: "Paris, France",
    continent: "Europe",
    constructionPeriod: "1971–1977",
    originalPurposeCategories: ["Learn & Create", "Gather & Entertain"],
    purposeTodayCategories: ["Learn & Experience", "Restore & Complete"],
  },
  {
    name: "Vanna Venturi House",
    location: "Philadelphia, United States",
    continent: "North America",
    constructionPeriod: "1962–1964",
    originalPurposeCategories: ["Live & Work"],
    purposeTodayCategories: ["Live & Work", "Visit & Preserve"],
  },
  {
    name: "Guggenheim Museum Bilbao",
    location: "Bilbao, Spain",
    continent: "Europe",
    constructionPeriod: "1993–1997",
    originalPurposeCategories: ["Learn & Create", "Gather & Entertain"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "Sagrada Família",
    location: "Barcelona, Spain",
    continent: "Europe",
    constructionPeriod: "1882–present",
    originalPurposeCategories: ["Worship"],
    purposeTodayCategories: [
      "Visit & Preserve",
      "Worship",
      "Restore & Complete",
    ],
  },
  {
    name: "Great Wall of China",
    location: "Northern China",
    continent: "Asia",
    constructionPeriod:
      "From c. 7th century BCE; major surviving sections 1368–1644",
    originalPurposeCategories: ["Defend", "Trade & Produce"],
    purposeTodayCategories: ["Visit & Preserve"],
  },
  {
    name: "Beijing National Stadium — Bird’s Nest",
    location: "Beijing, China",
    continent: "Asia",
    constructionPeriod: "2003–2008",
    originalPurposeCategories: ["Gather & Entertain"],
    purposeTodayCategories: ["Learn & Experience", "Visit & Preserve"],
  },
  {
    name: "Burj Khalifa",
    location: "Dubai, United Arab Emirates",
    continent: "Asia",
    constructionPeriod: "2004–2010",
    originalPurposeCategories: [
      "Live & Work",
      "Trade & Produce",
      "Gather & Entertain",
    ],
    purposeTodayCategories: ["Live & Work", "Visit & Preserve"],
  },
  {
    name: "The Shard",
    location: "London, United Kingdom",
    continent: "Europe",
    constructionPeriod: "2009–2012",
    originalPurposeCategories: ["Live & Work", "Trade & Produce"],
    purposeTodayCategories: ["Live & Work", "Visit & Preserve"],
  },
  {
    name: "Bosco Verticale",
    location: "Milan, Italy",
    continent: "Europe",
    constructionPeriod: "2009–2014",
    originalPurposeCategories: ["Live & Work"],
    purposeTodayCategories: ["Live & Work", "Visit & Preserve"],
  },
  {
    name: "National Museum of African American History and Culture",
    location: "Washington, D.C., United States",
    continent: "North America",
    constructionPeriod: "2012–2016",
    originalPurposeCategories: ["Learn & Create"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "Louvre Abu Dhabi",
    location: "Abu Dhabi, United Arab Emirates",
    continent: "Asia",
    constructionPeriod: "2009–2017",
    originalPurposeCategories: ["Learn & Create"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "Zeitz Museum of Contemporary Art Africa",
    location: "Cape Town, South Africa",
    continent: "Africa",
    constructionPeriod: "1924; converted 2013–2017",
    originalPurposeCategories: ["Learn & Create", "Trade & Produce"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "The Shed",
    location: "New York City, United States",
    continent: "North America",
    constructionPeriod: "2015–2019",
    originalPurposeCategories: ["Learn & Create", "Gather & Entertain"],
    purposeTodayCategories: ["Learn & Experience"],
  },
  {
    name: "Sara Kulturhus",
    location: "Skellefteå, Sweden",
    continent: "Europe",
    constructionPeriod: "2018–2021",
    originalPurposeCategories: [
      "Learn & Create",
      "Gather & Entertain",
      "Live & Work",
    ],
    purposeTodayCategories: ["Learn & Experience", "Live & Work"],
  },
  {
    name: "Museum of the Future",
    location: "Dubai, United Arab Emirates",
    continent: "Asia",
    constructionPeriod: "2016–2022",
    originalPurposeCategories: ["Learn & Create", "Gather & Entertain"],
    purposeTodayCategories: ["Visit & Preserve", "Learn & Experience"],
  },
  {
    name: "Living Landscape",
    location: "Reykjavík, Iceland",
    continent: "Europe",
    constructionPeriod: "2023–2026",
    originalPurposeCategories: ["Live & Work", "Trade & Produce"],
    purposeTodayCategories: ["Live & Work", "Restore & Complete"],
  },
  {
    name: "World of Volvo",
    location: "Gothenburg, Sweden",
    continent: "Europe",
    constructionPeriod: "2021–2024",
    originalPurposeCategories: [
      "Learn & Create",
      "Gather & Entertain",
      "Trade & Produce",
    ],
    purposeTodayCategories: ["Learn & Experience", "Live & Work"],
  },
  {
    name: "Timber House",
    location: "Toronto, Canada",
    continent: "North America",
    constructionPeriod: "TBD–ongoing",
    originalPurposeCategories: ["Live & Work"],
    purposeTodayCategories: ["Live & Work", "Restore & Complete"],
  },
  {
    name: "Naples Underground Central Station",
    location: "Naples, Italy",
    continent: "Europe",
    constructionPeriod: "Ongoing",
    originalPurposeCategories: ["Travel & Connect"],
    purposeTodayCategories: ["Govern & Serve", "Restore & Complete"],
  },
  {
    name: "Lucas Museum of Narrative Art",
    location: "Los Angeles, United States",
    continent: "North America",
    constructionPeriod: "2021–2026",
    originalPurposeCategories: ["Learn & Create"],
    purposeTodayCategories: ["Learn & Experience", "Restore & Complete"],
  },
  {
    name: "Centre des Cultures et Spiritualités Ewés",
    location: "Notsé, Togo",
    continent: "Africa",
    constructionPeriod: "2022–ongoing",
    originalPurposeCategories: [
      "Worship",
      "Learn & Create",
      "Gather & Entertain",
    ],
    purposeTodayCategories: [
      "Worship",
      "Learn & Experience",
      "Restore & Complete",
    ],
  },
];

export const continents = [
  "Africa",
  "Asia",
  "Europe",
  "North America",
  "South America",
  "Oceania",
];

export const originalPurposeCategories = [
  "Worship",
  "Remember & Honor",
  "Rule & Reside",
  "Govern & Serve",
  "Defend",
  "Learn & Create",
  "Gather & Entertain",
  "Trade & Produce",
  "Travel & Connect",
  "Live & Work",
];

export const purposeTodayCategories = [
  "Visit & Preserve",
  "Worship",
  "Learn & Experience",
  "Govern & Serve",
  "Live & Work",
  "Restore & Complete",
];
