export const buildings = [
  {
    name: "Göbekli Tepe",
    location: "Türkiye",
  },
  {
    name: "Great Pyramid of Giza",
    location: "Egypt",
  },
  {
    name: "Ziggurat of Ur",
    location: "Iraq",
  },
  {
    name: "Karnak Temple Complex",
    location: "Egypt",
  },
  {
    name: "Palace of Knossos",
    location: "Crete, Greece",
  },
  {
    name: "Treasury of Atreus",
    location: "Mycenae, Greece",
  },
  {
    name: "Sanchi Stupa",
    location: "India",
  },
  {
    name: "Parthenon",
    location: "Athens, Greece",
  },
  {
    name: "Apadana at Persepolis",
    location: "Iran",
  },
  {
    name: "Temple of Hephaestus",
    location: "Athens, Greece",
  },
  {
    name: "Great Stupa at Amaravati",
    location: "India",
  },
  {
    name: "Library of Celsus",
    location: "Ephesus, Türkiye",
  },
  {
    name: "Pantheon",
    location: "Rome, Italy",
  },
  {
    name: "Colosseum",
    location: "Rome, Italy",
  },
  {
    name: "Maison Carrée",
    location: "Nîmes, France",
  },
  {
    name: "Diocletian’s Palace",
    location: "Split, Croatia",
  },
  {
    name: "Great Bath of the Roman Baths",
    location: "Bath, United Kingdom",
  },
  {
    name: "Temple of the Inscriptions",
    location: "Palenque, Mexico",
  },
  {
    name: "Pyramid of the Sun",
    location: "Teotihuacan, Mexico",
  },
  {
    name: "Tikal Temple I",
    location: "Guatemala",
  },
  {
    name: "Hagia Sophia",
    location: "Istanbul, Türkiye",
  },
  {
    name: "Basilica of San Vitale",
    location: "Ravenna, Italy",
  },
  {
    name: "Hōryū-ji",
    location: "Nara Prefecture, Japan",
  },
  {
    name: "Dome of the Rock",
    location: "Jerusalem",
  },
  {
    name: "Umayyad Mosque",
    location: "Damascus, Syria",
  },
  {
    name: "Borobudur",
    location: "Java, Indonesia",
  },
  {
    name: "Prambanan",
    location: "Java, Indonesia",
  },
  {
    name: "Great Mosque of Samarra",
    location: "Iraq",
  },
  {
    name: "Aachen Cathedral",
    location: "Germany",
  },
  {
    name: "Jokhang Temple",
    location: "Lhasa, Tibet",
  },
  {
    name: "Brihadisvara Temple",
    location: "Thanjavur, India",
  },
  {
    name: "Angkor Wat",
    location: "Cambodia",
  },
  {
    name: "Durham Cathedral",
    location: "United Kingdom",
  },
  {
    name: "Chartres Cathedral",
    location: "France",
  },
  {
    name: "Hoysaleswara Temple",
    location: "Halebidu, India",
  },
  {
    name: "Church of St George, Lalibela",
    location: "Ethiopia",
  },
  {
    name: "Qutb Minar",
    location: "Delhi, India",
  },
  {
    name: "Konark Sun Temple",
    location: "Odisha, India",
  },
  {
    name: "Sainte-Chapelle",
    location: "Paris, France",
  },
  {
    name: "Great Enclosure at Great Zimbabwe",
    location: "Zimbabwe",
  },
  {
    name: "Alhambra",
    location: "Granada, Spain",
  },
  {
    name: "Forbidden City",
    location: "Beijing, China",
  },
  {
    name: "Kinkaku-ji",
    location: "Kyoto, Japan",
  },
  {
    name: "Machu Picchu",
    location: "Peru",
  },
  {
    name: "Florence Cathedral",
    location: "Italy",
  },
  {
    name: "Doge’s Palace",
    location: "Venice, Italy",
  },
  {
    name: "Elmina Castle",
    location: "Ghana",
  },
  {
    name: "Château de Chambord",
    location: "France",
  },
  {
    name: "St Peter’s Basilica",
    location: "Vatican City",
  },
  {
    name: "Humayun’s Tomb",
    location: "Delhi, India",
  },
  {
    name: "Süleymaniye Mosque",
    location: "Istanbul, Türkiye",
  },
  {
    name: "St Basil’s Cathedral",
    location: "Moscow, Russia",
  },
  {
    name: "Temple of Heaven",
    location: "Beijing, China",
  },
  {
    name: "Himeji Castle",
    location: "Japan",
  },
  {
    name: "Sultan Ahmed Mosque",
    location: "Istanbul, Türkiye",
  },
  {
    name: "Shah Mosque",
    location: "Isfahan, Iran",
  },
  {
    name: "Taj Mahal",
    location: "Agra, India",
  },
  {
    name: "Potala Palace",
    location: "Lhasa, Tibet",
  },
  {
    name: "Palace of Versailles",
    location: "France",
  },
  {
    name: "St Paul’s Cathedral",
    location: "London, United Kingdom",
  },
  {
    name: "Royal Palace of Caserta",
    location: "Italy",
  },
  {
    name: "Panthéon",
    location: "Paris, France",
  },
  {
    name: "Royal Crescent",
    location: "Bath, United Kingdom",
  },
  {
    name: "Monticello",
    location: "Virginia, United States",
  },
  {
    name: "United States Capitol",
    location: "Washington, D.C.",
  },
  {
    name: "Brandenburg Gate",
    location: "Berlin, Germany",
  },
  {
    name: "British Museum",
    location: "London, United Kingdom",
  },
  {
    name: "Palace of Westminster",
    location: "London, United Kingdom",
  },
  {
    name: "Bibliothèque Sainte-Geneviève",
    location: "Paris, France",
  },
  {
    name: "Crystal Palace",
    location: "London, United Kingdom",
  },
  {
    name: "Red House",
    location: "Bexleyheath, United Kingdom",
  },
  {
    name: "Galleria Vittorio Emanuele II",
    location: "Milan, Italy",
  },
  {
    name: "Chhatrapati Shivaji Maharaj Terminus",
    location: "Mumbai, India",
  },
  {
    name: "Eiffel Tower",
    location: "Paris, France",
  },
  {
    name: "Natural History Museum",
    location: "London, United Kingdom",
  },
  {
    name: "Hungarian Parliament Building",
    location: "Budapest, Hungary",
  },
  {
    name: "Wainwright Building",
    location: "St Louis, United States",
  },
  {
    name: "Flatiron Building",
    location: "New York, United States",
  },
  {
    name: "Casa Batlló",
    location: "Barcelona, Spain",
  },
  {
    name: "Glasgow School of Art, Mackintosh Building",
    location: "Glasgow, United Kingdom",
  },
  {
    name: "AEG Turbine Factory",
    location: "Berlin, Germany",
  },
  {
    name: "Robie House",
    location: "Chicago, United States",
  },
  {
    name: "Fagus Factory",
    location: "Alfeld, Germany",
  },
  {
    name: "Einstein Tower",
    location: "Potsdam, Germany",
  },
  {
    name: "Bauhaus Building",
    location: "Dessau, Germany",
  },
  {
    name: "Schröder House",
    location: "Utrecht, Netherlands",
  },
  {
    name: "Villa Savoye",
    location: "Poissy, France",
  },
  {
    name: "Barcelona Pavilion",
    location: "Barcelona, Spain",
  },
  {
    name: "Chrysler Building",
    location: "New York, United States",
  },
  {
    name: "Empire State Building",
    location: "New York, United States",
  },
  {
    name: "Fallingwater",
    location: "Pennsylvania, United States",
  },
  {
    name: "Paimio Sanatorium",
    location: "Finland",
  },
  {
    name: "Secretariat Building",
    location: "Chandigarh, India",
  },
  {
    name: "National Assembly Building",
    location: "Dhaka, Bangladesh",
  },
  {
    name: "Brasília Cathedral",
    location: "Brazil",
  },
  {
    name: "Sydney Opera House",
    location: "Sydney, Australia",
  },
  {
    name: "Habitat 67",
    location: "Montreal, Canada",
  },
  {
    name: "Centre Pompidou",
    location: "Paris, France",
  },
  {
    name: "Vanna Venturi House",
    location: "Philadelphia, United States",
  },
  {
    name: "Guggenheim Museum Bilbao",
    location: "Bilbao, Spain",
  },
  {
    name: "Sagrada Família",
    location: "Barcelona, Spain",
  },
  {
    name: "Great Wall of China",
    location: "Northern China",
  },
  {
    name: "Beijing National Stadium — Bird’s Nest",
    location: "Beijing, China",
  },
  {
    name: "Burj Khalifa",
    location: "Dubai, United Arab Emirates",
  },
  {
    name: "The Shard",
    location: "London, United Kingdom",
  },
  {
    name: "Bosco Verticale",
    location: "Milan, Italy",
  },
  {
    name: "National Museum of African American History and Culture",
    location: "Washington, D.C., United States",
  },
  {
    name: "Louvre Abu Dhabi",
    location: "Abu Dhabi, United Arab Emirates",
  },
  {
    name: "Zeitz Museum of Contemporary Art Africa",
    location: "Cape Town, South Africa",
  },
  {
    name: "The Shed",
    location: "New York City, United States",
  },
  {
    name: "Sara Kulturhus",
    location: "Skellefteå, Sweden",
  },
  {
    name: "Museum of the Future",
    location: "Dubai, United Arab Emirates",
  },
  {
    name: "Living Landscape",
    location: "Reykjavík, Iceland",
  },
  {
    name: "World of Volvo",
    location: "Gothenburg, Sweden",
  },
  {
    name: "Timber House",
    location: "Toronto, Canada",
  },
  {
    name: "Naples Underground Central Station",
    location: "Naples, Italy",
  },
  {
    name: "Lucas Museum of Narrative Art",
    location: "Los Angeles, United States",
  },
  {
    name: "Centre des Cultures et Spiritualités Ewés",
    location: "Notsé, Togo",
  },
];

export const placeNouns = [
  "apadana",
  "basilica",
  "bath",
  "bibliothèque",
  "building",
  "capitol",
  "castle",
  "cathedral",
  "centre",
  "chapelle",
  "château",
  "church",
  "city",
  "colosseum",
  "complex",
  "dome",
  "enclosure",
  "factory",
  "galleria",
  "gate",
  "house",
  "kulturhus",
  "library",
  "maison",
  "minar",
  "mosque",
  "museum",
  "palace",
  "pantheon",
  "parliament",
  "pavilion",
  "pyramid",
  "sanatorium",
  "school",
  "secretariat",
  "shed",
  "station",
  "stadium",
  "stupa",
  "temple",
  "terminus",
  "tomb",
  "tower",
  "treasury",
  "villa",
  "wall",
  "wat",
  "ziggurat",
];

export const conceptNouns = [
  "art",
  "assembly",
  "bird",
  "crescent",
  "culture",
  "empire",
  "future",
  "habitat",
  "heaven",
  "history",
  "inscriptions",
  "landscape",
  "narrative",
  "nest",
  "opera",
  "rock",
  "shard",
  "spiritualities",
  "state",
  "sun",
  "timber",
  "turbine",
  "wall",
  "water",
  "world",
];

export const properNames = [
  "Abu Dhabi",
  "Aachen",
  "AEG",
  "Africa",
  "African American",
  "Ahmed",
  "Alhambra",
  "Amaravati",
  "Angkor Wat",
  "Atreus",
  "Barcelona",
  "Basil",
  "Batlló",
  "Bauhaus",
  "Beijing",
  "Bilbao",
  "Borobudur",
  "Bosco Verticale",
  "Brandenburg",
  "Brasília",
  "Brihadisvara",
  "Burj Khalifa",
  "Carrée",
  "Caserta",
  "Celsus",
  "Chambord",
  "Chartres",
  "China",
  "Chhatrapati Shivaji Maharaj",
  "Chrysler",
  "Diocletian",
  "Durham",
  "Eiffel",
  "Einstein",
  "Elmina",
  "Ewés",
  "Fagus",
  "Florence",
  "Giza",
  "Glasgow",
  "Göbekli Tepe",
  "Great Zimbabwe",
  "Guggenheim",
  "Hagia Sophia",
  "Hephaestus",
  "Himeji",
  "Hōryū-ji",
  "Hoysaleswara",
  "Humayun",
  "Jokhang",
  "Karnak",
  "Khalifa",
  "Kinkaku-ji",
  "Knossos",
  "Konark",
  "Lalibela",
  "Louvre",
  "Lucas",
  "Machu Picchu",
  "Mackintosh",
  "Mahal",
  "Monticello",
  "Naples",
  "Paimio",
  "Parthenon",
  "Paul",
  "Persepolis",
  "Peter",
  "Pompidou",
  "Potala",
  "Prambanan",
  "Qutb",
  "Robie",
  "Roman",
  "Samarra",
  "San Vitale",
  "Sanchi",
  "Sara",
  "Savoye",
  "Schröder",
  "Shah",
  "Sydney",
  "Sagrada Família",
  "Sainte-Geneviève",
  "Süleymaniye",
  "Sultan Ahmed",
  "Taj Mahal",
  "Tikal",
  "Ur",
  "Umayyad",
  "United States",
  "Vanna Venturi",
  "Versailles",
  "Vittorio Emanuele II",
  "Volvo",
  "Wainwright",
  "Westminster",
  "Zeitz",
];

export const qualityWords = [
  "central",
  "contemporary",
  "crystal",
  "falling",
  "flatiron",
  "forbidden",
  "great",
  "living",
  "national",
  "natural",
  "narrative",
  "red",
  "royal",
  "sagrada",
  "underground",
  "united",
  "verticale",
];
