const buildings = [
  "Royal Ontario Museum",
  "Museum of Islamic Art",
  "Art Gallery of Ontario",
  "Ontario Science Centre",
  "Centre Pompidou",
  "Pompidou Centre-Metz",
  "Burj Khalifa",
  "Khalifa International Stadium",
  "Stadium Australia",
  "Australia Square",
  "Colosseum",
  "National Gallery",
  "Gallery of Modern Art",
  "Modern Art Museum of Fort Worth",
  "Art Institute of Chicago",
  "Chicago Cultural Center",
  "Center for Architecture",
  "Oslo Opera House",
  "House of the Blackheads",
  "Blackheads House Museum",
  "Art Gallery of New South Wales",
  "Wales Millennium Centre",
  "Lotus Temple",
  "Temple of Heaven",
  "Heavenly Gate",
  "Gate Tower Building",
  "Guggenheim Museum",
  "Tower Bridge",
  "Bridge of Sighs",
  "Taj Mahal",
  "Taj Mahal Palace Hotel",
];
